// <auto-generated />
using System;
using HCL.NotificationSubscriptionServer.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HCL.NotificationSubscriptionServer.API.DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230416000115_create")]
    partial class create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HCL.NotificationSubscriptionServer.API.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pk_notification_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("HCL.NotificationSubscriptionServer.API.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pk_relationship_id");

                    b.Property<Guid>("AccountMasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_master_id");

                    b.Property<Guid>("AccountSlaveId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_slave_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("relationship_status");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("relationships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
