version: '3.4'

networks:
  dev:
    driver: bridge

services:
  hcl.notificationsubscriptionserver.api:
    image: ${DOCKER_REGISTRY-}hclnotificationsubscriptionserverapi
    depends_on: 
      - app_db_hcl_notification_relation
    container_name: HCL.NotificationServer
    build:
      context: .
      dockerfile: HCL.NotificationSubscriptionServer.API/Dockerfile
    environment:
      - ConnectionStrings__NpgConnectionString=User Id=postgres; Password=pg; Server=app_db_hcl_notification_relation; Port=5432; Database=HCL_NotificationServer; IntegratedSecurity=true; Pooling=true;
    networks:
      - dev

  app_db_hcl_notification_relation: 
    image: postgres:latest
    container_name: app_db_hcl_notification_relation
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=HCL_NotificationServer
      - KafkaSettings__BootstrapServers=localhost:9093
      - KafkaSettings__Topic=new_article
      - KafkaSettings__User=kafka
      - KafkaSettings__Password=kafka
    ports:
      - "5473:5432"
    restart: always
    volumes:
      - app_db_hcl_notification_relation:/var/lib/postgresql/data_notification
    networks:
      - dev
            
volumes:
  app_db_hcl_notification_relation: